spring:
  datasource:
    url: "jdbc:postgresql://localhost:5000/to-do-db"
    username: user
    password: password

security:
  jwt:
    issuer: to-do-app-development
    exp-time: 900

  hash-strength: 14
  Cors:
    allow-credentials: true
    allowed-origins:
      - "http://localhost:5173"
    mapping-pattern: "/**"

