spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/todo-database"
    username: user
    password: password

security:
  jwt:
    issuer: to-do-app-development
    access-exp-time: 900
    refresh-exp-days: 7

  hash-strength: 14
  Cors:
    allow-credentials: true
    allowed-origins:
      - "http://localhost:5173"
    mapping-pattern: "/**"
  secure-cookies: false

